QuTech-Delft/qne-adk

src/cli/command_list.py
src/cli/decorators.py
src/cli/exceptions.py
src/tests/test_command_list.py

* Catch exceptions for all commands
* Print an error message for qne cli exception
* Print an unhandled exception message for  other exceptions
* Removed periods for some error or info messages

[QNEBE-390] Handle exceptions

---

src/cli/api/local_api.py
src/cli/command_list.py
src/cli/command_processor.py
src/cli/exceptions.py
src/cli/managers/config_manager.py
src/cli/utils.py
src/tests/api/test_local_api.py
src/tests/managers/test_config_manager.py
src/tests/test_command_list.py
src/tests/test_command_processor.py

Fixed bugs and did some boyscouting:
* Fixed tickets QNEBE-410, QNEBE-409, QNEBE-408, QNEBE-407, QNEBE-405, QNEBE-404, QNEBE-389, QNEBE-391
* Some unit tests had side effects, e.g files were created.
* Did some work on consistency (e.g. on output text)
* __is_application_unique removed, now is application_exists (which it actually was)
* Added some docstring here and there
* Sometimes did some reordering to combine methods theat are related. This makes reviewing more difficult. Sorry for that.

[QNEBE-410-409-408-407-405-404-389-391] Solved some bugs

---

LICENSE
setup.py

* Changed license to MIT
* Added copyright notice to setup.py

[QNEBE-386] MIT License

---

src/cli/command_list.py
src/cli/exceptions.py
src/cli/settings.py
src/tests/test_command_list.py

* Removed references to remote from the commands
* Exception command not implemented when a command is used that is not yet implemented, instead of weird empty functionality

[QNEBE-390] Local only

---

src/cli/api/local_api.py
src/cli/command_list.py
src/cli/command_processor.py
src/cli/exceptions.py
src/cli/managers/config_manager.py
src/cli/managers/roundset_manager.py
src/cli/networks/channels.json
src/cli/networks/nodes.json
src/cli/schema/experiments/asset.json
src/cli/schema/experiments/experiment.json
src/cli/schema/networks/channel_asset.json
src/cli/schema/networks/network_asset.json
src/cli/schema/networks/node_asset.json
src/cli/schema/networks/qubit.json
src/cli/schema/networks/roletemplate.json
src/cli/schema/networks/template.json
src/cli/validators.py
src/tests/api/test_local_api.py
src/tests/managers/test_config_manager.py
src/tests/schema/networks/test_network_asset.py
src/tests/test_command_list.py
src/tests/test_validators.py

FGr:
* did the rest of the review comments I had
* did some boyscouting in consistency using '' and ""
* changed some uses of os.path.xxx to Path.xxx (is_file, exists)
* changed some uses of is_file, is_dir or exists to what is really checked (file or dir or don't care)
* added test for path case sensitive check
* added 100% tests for validator.py
* solved some mypy and pylint errors

Experiment validate command

---

src/cli/utils.py

- Restructured the creation of the application.json. Each role will have it's seperate input and the last input includes all roles.
- config_manager=None is added as parameter to the main() of the generated python files

[QNEBE-419] Update content application.json

---

src/cli/api/local_api.py
src/cli/command_list.py
src/tests/api/test_local_api.py
src/tests/test_command_list.py

* Made the error messages more specific to let the application developer know wht to do
* Fixed unit test with assignments instead of tests!
* Added unit test to reach 100% test coverage for the method touched
* Some PEP8 boyscouting

[QNEBE-426] application error messages more specific and tested

---

src/adk/command_list.py

* completion options disabled
* result command removed

[QNEBE-439] Fix qne --help

---

setup.py
src/adk/api/local_api.py

* Added package data files
* Added some extra stuff to setup metadata
* Added __init__ in parsers (otherwise these files are not installed)
* Suddenly an extra mypy error appeared in superfluous cast

[QNEBE-341] Getting ready for pypi

---

src/adk/api/local_api.py
src/adk/command_list.py
src/adk/command_processor.py
src/adk/managers/config_manager.py
src/adk/managers/roundset_manager.py
src/adk/networks/nodes.json
src/tests/api/test_local_api.py
src/tests/managers/test_config_manager.py
src/tests/test_command_list.py
src/tests/test_command_processor.py

Added some constency to the function application validate, experiment validate, experiment run and experiment result where now the application/experiment name can be given as an input parameter to the commands.

[QNEBE-438] Command consistency

---

.pylintrc
README.md
docs/introduction.rst
src/adk/api/local_api.py
src/adk/api/qne_client.py
src/adk/api/remote_api.py
src/adk/command_list.py
src/adk/command_processor.py
src/adk/exceptions.py
src/adk/schema/applications/manifest.json
src/adk/type_aliases.py
src/tests/api/test_local_api.py
src/tests/api/test_remote_api.py
src/tests/test_command_list.py
src/tests/test_command_processor.py

* Added publish application
* Updated readme and readthe docs (also changed order of commands a bit)
* Fixed type for AppResultType
* Some methods made staticmethods
* Added docstrings to some undocumented methods
* Added client code for changed or not yet supported api-router endpoints (partial update app_version + list app_versions for application)
* Removed some unused instance variables in remote_api
* Added __get_application that tries to get application via id first and then slug second
* Added (and used) exception AppConfigNotFound
* Added unit tests for application upload
* Added unit tests for application publish
* Removed pylint checks for unit tests

[QNEBE-367] Publish application

---

README.md
docs/introduction.rst
src/adk/api/local_api.py
src/adk/api/qne_client.py
src/adk/api/remote_api.py
src/adk/command_list.py
src/adk/command_processor.py
src/adk/managers/resource_manager.py
src/adk/schema/applications/application.json
src/adk/utils.py
src/tests/api/test_local_api.py
src/tests/api/test_remote_api.py
src/tests/test_command_list.py
src/tests/test_command_processor.py

* Command qne clone to clone remote or local application
* Solved bug in schema (template scale_value can be a string of number)
* Added unit tests for clone and some more to reach 70% code coverage
* Added documentation for clone command (readme and readthedoc)

[QNEBE-496] Application clone command

---

src/adk/api/local_api.py
src/adk/api/qne_client.py
src/adk/api/remote_api.py
src/adk/command_list.py
src/adk/generators/network_generator.py
src/tests/api/test_qne_client.py
src/tests/test_command_list.py

* Pagination added when getting the applications list
* Unit test added for this method in qne_client
* Deepcopy added while creating asset_network to prevent overwriting the original network_data (for reentrance purposes)

[QNEBE-557] Application endpoint changes

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/github-ci.yaml

* Added templates for bug and feature request
* Changed filename to github-ci
* Added dependency to test build and test publish to pypi (to prevent a publish to pypi when the tests fail)

[QNEBE-NNN] Added templates, changed filename and added dependency to test build

---

.github/dependabot.yml
.github/workflows/github-ci.yaml

This PR increments GitHub Actions versions.
It also includes a dependabot.yml configuration that will automatically update these versions going forward to reduce the risk of version drift.

[SDS-808] Increment GitHub actions versions

---

src/adk/api/qne_client.py
src/adk/exceptions.py
src/adk/managers/resource_manager.py
src/tests/managers/test_resource_manager.py

* Fix from https://github.com/QuTech-Delft/qne-adk/pull/51 adjusted to pass the pipe lines
* Added unit tests for the changes
* Completed unit tests for resource_manager

[QNEBE-666] Fix for cve-2007-4559

---

.github/dependabot.yml

* Let dependabot also update pip packages
* Reviewer fixed: may be changed in the future

[QNEBE-NNN] Fix dependabot

---

src/adk/api/local_api.py
src/adk/command_list.py
src/adk/command_processor.py
src/tests/api/test_local_api.py
src/tests/test_command_list.py
src/tests/test_command_processor.py

* Added parameter --update to run command
* Changed implicit update of application files for the new experiment run to an explicit update based on the parameter
* Added an application validate before updating application files to the experiment
* Added unit tests for the changed functionality

[QNEBE-677] Experiment run --update

---

.github/workflows/github-ci.yaml
.github/workflows/publish.yaml
setup.py
src/adk/parsers/output_converter.py

* fix for mypy error in pipeline
* separated dev pipeline actions and separate action for master (publish)

[QNEBE-NNN] Quick fix for mypy error in pipeline, moved publish to separate action

---

setup.py
src/adk/settings.py

Update pydantic version to 2.1.1; use new pydantic-settings module.

[QNEBE-NNN] Fix CI pipeline pydantic errors

---

src/adk/schema/applications/application.json
src/adk/schema/applications/network.json
src/adk/schema/applications/result.json
src/adk/schema/experiments/experiment.json

* Updated version number when needed
* Fixed some errors in schema definitions

[QNEBE-735] Schema definitions updated

---

src/adk/api/qne_client.py

https://github.com/QuTech-Delft/qne-adk/pull/81 (suddenly) fails on this because of newest pylint
* New pylint more strict on duplicate code. This piece of code is in 2 more or less unrelated classes.

[QNEBE-NNN] fix for pylint update
